version: '3.8'
services:
  survey-db:
    image: postgres:15.1
    container_name: survey-db
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=survey_db
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: app
    depends_on:
      - survey-db
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - app-network

volumes:
  postgres:
    driver: local

networks:
  app-network:
    driver: bridge
